#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ABCEnjoy.Resource", IsApplication=true)]

namespace ABCEnjoy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int abc_fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int abc_grow_fade_in_from_bottom = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int abc_popup_enter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int abc_popup_exit = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int abc_shrink_fade_out_from_bottom = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int abc_slide_in_bottom = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int abc_slide_in_top = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int abc_slide_out_bottom = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int abc_slide_out_top = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int tooltip_enter = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tooltip_exit = 2131034123;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070003
			public const int abc_action_bar_embed_tabs = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int abc_action_bar_embed_tabs_pre_jb = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int abc_action_bar_expanded_action_views_exclusive = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int abc_allow_stacked_button_bar = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int abc_config_actionMenuItemAllCaps = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int abc_config_allowActionMenuItemTextWithIcon = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int abc_config_closeDialogWhenTouchOutside = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131165191;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0b003a
			public const int abc_background_cache_hint_selector_material_dark = 2131427386;
			
			// aapt resource value: 0x7f0b003b
			public const int abc_background_cache_hint_selector_material_light = 2131427387;
			
			// aapt resource value: 0x7f0b0000
			public const int abc_input_method_navigation_guard = 2131427328;
			
			// aapt resource value: 0x7f0b003c
			public const int abc_primary_text_disable_only_material_dark = 2131427388;
			
			// aapt resource value: 0x7f0b003d
			public const int abc_primary_text_disable_only_material_light = 2131427389;
			
			// aapt resource value: 0x7f0b003e
			public const int abc_primary_text_material_dark = 2131427390;
			
			// aapt resource value: 0x7f0b003f
			public const int abc_primary_text_material_light = 2131427391;
			
			// aapt resource value: 0x7f0b0040
			public const int abc_search_url_text = 2131427392;
			
			// aapt resource value: 0x7f0b0001
			public const int abc_search_url_text_normal = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int abc_search_url_text_pressed = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int abc_search_url_text_selected = 2131427331;
			
			// aapt resource value: 0x7f0b0041
			public const int abc_secondary_text_material_dark = 2131427393;
			
			// aapt resource value: 0x7f0b0042
			public const int abc_secondary_text_material_light = 2131427394;
			
			// aapt resource value: 0x7f0b0004
			public const int accent_material_dark = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int accent_material_light = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int background_floating_material_dark = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int background_floating_material_light = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int background_material_dark = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int background_material_light = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int bright_foreground_disabled_material_dark = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int bright_foreground_disabled_material_light = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int bright_foreground_inverse_material_dark = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int bright_foreground_inverse_material_light = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int bright_foreground_material_dark = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int bright_foreground_material_light = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int button_material_dark = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int button_material_light = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int dim_foreground_disabled_material_dark = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int dim_foreground_disabled_material_light = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int dim_foreground_material_dark = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int dim_foreground_material_light = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int foreground_material_dark = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int foreground_material_light = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int highlighted_text_material_dark = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int highlighted_text_material_light = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int hint_foreground_material_dark = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int hint_foreground_material_light = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int material_blue_grey_800 = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int material_blue_grey_900 = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int material_blue_grey_950 = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int material_deep_teal_200 = 2131427359;
			
			// aapt resource value: 0x7f0b0020
			public const int material_deep_teal_500 = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int material_grey_100 = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int material_grey_300 = 2131427362;
			
			// aapt resource value: 0x7f0b0023
			public const int material_grey_50 = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int material_grey_600 = 2131427364;
			
			// aapt resource value: 0x7f0b0025
			public const int material_grey_800 = 2131427365;
			
			// aapt resource value: 0x7f0b0026
			public const int material_grey_850 = 2131427366;
			
			// aapt resource value: 0x7f0b0027
			public const int material_grey_900 = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int primary_dark_material_dark = 2131427368;
			
			// aapt resource value: 0x7f0b0029
			public const int primary_dark_material_light = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int primary_material_dark = 2131427370;
			
			// aapt resource value: 0x7f0b002b
			public const int primary_material_light = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int primary_text_default_material_dark = 2131427372;
			
			// aapt resource value: 0x7f0b002d
			public const int primary_text_default_material_light = 2131427373;
			
			// aapt resource value: 0x7f0b002e
			public const int primary_text_disabled_material_dark = 2131427374;
			
			// aapt resource value: 0x7f0b002f
			public const int primary_text_disabled_material_light = 2131427375;
			
			// aapt resource value: 0x7f0b0030
			public const int ripple_material_dark = 2131427376;
			
			// aapt resource value: 0x7f0b0031
			public const int ripple_material_light = 2131427377;
			
			// aapt resource value: 0x7f0b0032
			public const int secondary_text_default_material_dark = 2131427378;
			
			// aapt resource value: 0x7f0b0033
			public const int secondary_text_default_material_light = 2131427379;
			
			// aapt resource value: 0x7f0b0034
			public const int secondary_text_disabled_material_dark = 2131427380;
			
			// aapt resource value: 0x7f0b0035
			public const int secondary_text_disabled_material_light = 2131427381;
			
			// aapt resource value: 0x7f0b0036
			public const int switch_thumb_disabled_material_dark = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int switch_thumb_disabled_material_light = 2131427383;
			
			// aapt resource value: 0x7f0b0043
			public const int switch_thumb_material_dark = 2131427395;
			
			// aapt resource value: 0x7f0b0044
			public const int switch_thumb_material_light = 2131427396;
			
			// aapt resource value: 0x7f0b0038
			public const int switch_thumb_normal_material_dark = 2131427384;
			
			// aapt resource value: 0x7f0b0039
			public const int switch_thumb_normal_material_light = 2131427385;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f08000d
			public const int abc_action_bar_content_inset_material = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int abc_action_bar_default_height_material = 2131230721;
			
			// aapt resource value: 0x7f08000e
			public const int abc_action_bar_default_padding_end_material = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int abc_action_bar_default_padding_start_material = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int abc_action_bar_icon_vertical_padding_material = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int abc_action_bar_overflow_padding_end_material = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int abc_action_bar_overflow_padding_start_material = 2131230739;
			
			// aapt resource value: 0x7f080002
			public const int abc_action_bar_progress_bar_size = 2131230722;
			
			// aapt resource value: 0x7f080014
			public const int abc_action_bar_stacked_max_height = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int abc_action_bar_stacked_tab_max_width = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int abc_action_bar_subtitle_bottom_margin_material = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int abc_action_bar_subtitle_top_margin_material = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int abc_action_button_min_height_material = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int abc_action_button_min_width_material = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int abc_action_button_min_width_overflow_material = 2131230746;
			
			// aapt resource value: 0x7f080000
			public const int abc_alert_dialog_button_bar_height = 2131230720;
			
			// aapt resource value: 0x7f08001b
			public const int abc_button_inset_horizontal_material = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int abc_button_inset_vertical_material = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int abc_button_padding_horizontal_material = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int abc_button_padding_vertical_material = 2131230750;
			
			// aapt resource value: 0x7f080005
			public const int abc_config_prefDialogWidth = 2131230725;
			
			// aapt resource value: 0x7f08001f
			public const int abc_control_corner_material = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int abc_control_inset_material = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int abc_control_padding_material = 2131230753;
			
			// aapt resource value: 0x7f080006
			public const int abc_dialog_fixed_height_major = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int abc_dialog_fixed_height_minor = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int abc_dialog_fixed_width_major = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int abc_dialog_fixed_width_minor = 2131230729;
			
			// aapt resource value: 0x7f080022
			public const int abc_dialog_list_padding_vertical_material = 2131230754;
			
			// aapt resource value: 0x7f08000a
			public const int abc_dialog_min_width_major = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int abc_dialog_min_width_minor = 2131230731;
			
			// aapt resource value: 0x7f080023
			public const int abc_dialog_padding_material = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int abc_dialog_padding_top_material = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int abc_disabled_alpha_material_dark = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int abc_disabled_alpha_material_light = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int abc_dropdownitem_icon_width = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int abc_dropdownitem_text_padding_left = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int abc_dropdownitem_text_padding_right = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int abc_edit_text_inset_bottom_material = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int abc_edit_text_inset_horizontal_material = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int abc_edit_text_inset_top_material = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int abc_floating_window_z = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int abc_list_item_padding_horizontal_material = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int abc_panel_menu_list_width = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int abc_search_view_preferred_width = 2131230768;
			
			// aapt resource value: 0x7f08000c
			public const int abc_search_view_text_min_width = 2131230732;
			
			// aapt resource value: 0x7f080031
			public const int abc_seekbar_track_background_height_material = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int abc_seekbar_track_progress_height_material = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int abc_select_dialog_padding_start_material = 2131230771;
			
			// aapt resource value: 0x7f080010
			public const int abc_switch_padding = 2131230736;
			
			// aapt resource value: 0x7f080034
			public const int abc_text_size_body_1_material = 2131230772;
			
			// aapt resource value: 0x7f080035
			public const int abc_text_size_body_2_material = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int abc_text_size_button_material = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int abc_text_size_caption_material = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int abc_text_size_display_1_material = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int abc_text_size_display_2_material = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public const int abc_text_size_display_3_material = 2131230778;
			
			// aapt resource value: 0x7f08003b
			public const int abc_text_size_display_4_material = 2131230779;
			
			// aapt resource value: 0x7f08003c
			public const int abc_text_size_headline_material = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int abc_text_size_large_material = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public const int abc_text_size_medium_material = 2131230782;
			
			// aapt resource value: 0x7f08003f
			public const int abc_text_size_menu_material = 2131230783;
			
			// aapt resource value: 0x7f080040
			public const int abc_text_size_small_material = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int abc_text_size_subhead_material = 2131230785;
			
			// aapt resource value: 0x7f080003
			public const int abc_text_size_subtitle_material_toolbar = 2131230723;
			
			// aapt resource value: 0x7f080042
			public const int abc_text_size_title_material = 2131230786;
			
			// aapt resource value: 0x7f080004
			public const int abc_text_size_title_material_toolbar = 2131230724;
			
			// aapt resource value: 0x7f080043
			public const int disabled_alpha_material_dark = 2131230787;
			
			// aapt resource value: 0x7f080044
			public const int disabled_alpha_material_light = 2131230788;
			
			// aapt resource value: 0x7f080045
			public const int highlight_alpha_material_colored = 2131230789;
			
			// aapt resource value: 0x7f080046
			public const int highlight_alpha_material_dark = 2131230790;
			
			// aapt resource value: 0x7f080047
			public const int highlight_alpha_material_light = 2131230791;
			
			// aapt resource value: 0x7f080048
			public const int notification_large_icon_height = 2131230792;
			
			// aapt resource value: 0x7f080049
			public const int notification_large_icon_width = 2131230793;
			
			// aapt resource value: 0x7f08004a
			public const int notification_subtext_size = 2131230794;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f04001e
			public const int notification_template_lines = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int notification_template_media = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int notification_template_part_chronometer = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int notification_template_part_time = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int select_dialog_item_material = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int select_dialog_multichoice_material = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int select_dialog_singlechoice_material = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int support_simple_spinner_dropdown_item = 2130968613;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
