#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ABCEnjoy.Resource", IsApplication=true)]

namespace ABCEnjoy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.RangeSlider.Resource.Attribute.absoluteMaxValue = global::ABCEnjoy.Resource.Attribute.absoluteMaxValue;
			global::Xamarin.RangeSlider.Resource.Attribute.absoluteMinValue = global::ABCEnjoy.Resource.Attribute.absoluteMinValue;
			global::Xamarin.RangeSlider.Resource.Attribute.activateOnDefaultValues = global::ABCEnjoy.Resource.Attribute.activateOnDefaultValues;
			global::Xamarin.RangeSlider.Resource.Attribute.activeColor = global::ABCEnjoy.Resource.Attribute.activeColor;
			global::Xamarin.RangeSlider.Resource.Attribute.alwaysActive = global::ABCEnjoy.Resource.Attribute.alwaysActive;
			global::Xamarin.RangeSlider.Resource.Attribute.barHeight = global::ABCEnjoy.Resource.Attribute.barHeight;
			global::Xamarin.RangeSlider.Resource.Attribute.defaultColor = global::ABCEnjoy.Resource.Attribute.defaultColor;
			global::Xamarin.RangeSlider.Resource.Attribute.internalPadding = global::ABCEnjoy.Resource.Attribute.internalPadding;
			global::Xamarin.RangeSlider.Resource.Attribute.materialUI = global::ABCEnjoy.Resource.Attribute.materialUI;
			global::Xamarin.RangeSlider.Resource.Attribute.maxThumbHidden = global::ABCEnjoy.Resource.Attribute.maxThumbHidden;
			global::Xamarin.RangeSlider.Resource.Attribute.minThumbHidden = global::ABCEnjoy.Resource.Attribute.minThumbHidden;
			global::Xamarin.RangeSlider.Resource.Attribute.showRangeLabels = global::ABCEnjoy.Resource.Attribute.showRangeLabels;
			global::Xamarin.RangeSlider.Resource.Attribute.stepValue = global::ABCEnjoy.Resource.Attribute.stepValue;
			global::Xamarin.RangeSlider.Resource.Attribute.stepValueContinuously = global::ABCEnjoy.Resource.Attribute.stepValueContinuously;
			global::Xamarin.RangeSlider.Resource.Attribute.textAboveThumbsColor = global::ABCEnjoy.Resource.Attribute.textAboveThumbsColor;
			global::Xamarin.RangeSlider.Resource.Attribute.textSize = global::ABCEnjoy.Resource.Attribute.textSize;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbDisabled = global::ABCEnjoy.Resource.Attribute.thumbDisabled;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbNormal = global::ABCEnjoy.Resource.Attribute.thumbNormal;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbPressed = global::ABCEnjoy.Resource.Attribute.thumbPressed;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadow = global::ABCEnjoy.Resource.Attribute.thumbShadow;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowBlur = global::ABCEnjoy.Resource.Attribute.thumbShadowBlur;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowColor = global::ABCEnjoy.Resource.Attribute.thumbShadowColor;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowXOffset = global::ABCEnjoy.Resource.Attribute.thumbShadowXOffset;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowYOffset = global::ABCEnjoy.Resource.Attribute.thumbShadowYOffset;
			global::Xamarin.RangeSlider.Resource.Attribute.valuesAboveThumbs = global::ABCEnjoy.Resource.Attribute.valuesAboveThumbs;
			global::Xamarin.RangeSlider.Resource.String.app_name = global::ABCEnjoy.Resource.String.app_name;
			global::Xamarin.RangeSlider.Resource.String.demo_max_label = global::ABCEnjoy.Resource.String.demo_max_label;
			global::Xamarin.RangeSlider.Resource.String.demo_min_label = global::ABCEnjoy.Resource.String.demo_min_label;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl = global::ABCEnjoy.Resource.Styleable.RangeSliderControl;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_absoluteMaxValue = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_absoluteMaxValue;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_absoluteMinValue = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_absoluteMinValue;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_activateOnDefaultValues = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_activateOnDefaultValues;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_activeColor = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_activeColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_alwaysActive = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_alwaysActive;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_barHeight = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_barHeight;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_defaultColor = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_defaultColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_internalPadding = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_internalPadding;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_materialUI = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_materialUI;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_maxThumbHidden = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_maxThumbHidden;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_minThumbHidden = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_minThumbHidden;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_showRangeLabels = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_showRangeLabels;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_stepValue = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_stepValue;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_stepValueContinuously = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_stepValueContinuously;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_textAboveThumbsColor = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_textAboveThumbsColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_textSize = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_textSize;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbDisabled = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbDisabled;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbNormal = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbNormal;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbPressed = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbPressed;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadow = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbShadow;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowBlur = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbShadowBlur;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowColor = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbShadowColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowXOffset = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbShadowXOffset;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowYOffset = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_thumbShadowYOffset;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_valuesAboveThumbs = global::ABCEnjoy.Resource.Styleable.RangeSliderControl_valuesAboveThumbs;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int abc_fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int abc_grow_fade_in_from_bottom = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int abc_popup_enter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int abc_popup_exit = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int abc_shrink_fade_out_from_bottom = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int abc_slide_in_bottom = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int abc_slide_in_top = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int abc_slide_out_bottom = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int abc_slide_out_top = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int design_bottom_sheet_slide_in = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int design_bottom_sheet_slide_out = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int design_fab_in = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int design_fab_out = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int design_snackbar_in = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int design_snackbar_out = 2131034127;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01011b
			public const int absoluteMaxValue = 2130772251;
			
			// aapt resource value: 0x7f01011a
			public const int absoluteMinValue = 2130772250;
			
			// aapt resource value: 0x7f01003f
			public const int actionBarDivider = 2130772031;
			
			// aapt resource value: 0x7f010040
			public const int actionBarItemBackground = 2130772032;
			
			// aapt resource value: 0x7f010039
			public const int actionBarPopupTheme = 2130772025;
			
			// aapt resource value: 0x7f01003e
			public const int actionBarSize = 2130772030;
			
			// aapt resource value: 0x7f01003b
			public const int actionBarSplitStyle = 2130772027;
			
			// aapt resource value: 0x7f01003a
			public const int actionBarStyle = 2130772026;
			
			// aapt resource value: 0x7f010035
			public const int actionBarTabBarStyle = 2130772021;
			
			// aapt resource value: 0x7f010034
			public const int actionBarTabStyle = 2130772020;
			
			// aapt resource value: 0x7f010036
			public const int actionBarTabTextStyle = 2130772022;
			
			// aapt resource value: 0x7f01003c
			public const int actionBarTheme = 2130772028;
			
			// aapt resource value: 0x7f01003d
			public const int actionBarWidgetTheme = 2130772029;
			
			// aapt resource value: 0x7f010059
			public const int actionButtonStyle = 2130772057;
			
			// aapt resource value: 0x7f010055
			public const int actionDropDownStyle = 2130772053;
			
			// aapt resource value: 0x7f0100a7
			public const int actionLayout = 2130772135;
			
			// aapt resource value: 0x7f010041
			public const int actionMenuTextAppearance = 2130772033;
			
			// aapt resource value: 0x7f010042
			public const int actionMenuTextColor = 2130772034;
			
			// aapt resource value: 0x7f010045
			public const int actionModeBackground = 2130772037;
			
			// aapt resource value: 0x7f010044
			public const int actionModeCloseButtonStyle = 2130772036;
			
			// aapt resource value: 0x7f010047
			public const int actionModeCloseDrawable = 2130772039;
			
			// aapt resource value: 0x7f010049
			public const int actionModeCopyDrawable = 2130772041;
			
			// aapt resource value: 0x7f010048
			public const int actionModeCutDrawable = 2130772040;
			
			// aapt resource value: 0x7f01004d
			public const int actionModeFindDrawable = 2130772045;
			
			// aapt resource value: 0x7f01004a
			public const int actionModePasteDrawable = 2130772042;
			
			// aapt resource value: 0x7f01004f
			public const int actionModePopupWindowStyle = 2130772047;
			
			// aapt resource value: 0x7f01004b
			public const int actionModeSelectAllDrawable = 2130772043;
			
			// aapt resource value: 0x7f01004c
			public const int actionModeShareDrawable = 2130772044;
			
			// aapt resource value: 0x7f010046
			public const int actionModeSplitBackground = 2130772038;
			
			// aapt resource value: 0x7f010043
			public const int actionModeStyle = 2130772035;
			
			// aapt resource value: 0x7f01004e
			public const int actionModeWebSearchDrawable = 2130772046;
			
			// aapt resource value: 0x7f010037
			public const int actionOverflowButtonStyle = 2130772023;
			
			// aapt resource value: 0x7f010038
			public const int actionOverflowMenuStyle = 2130772024;
			
			// aapt resource value: 0x7f0100a9
			public const int actionProviderClass = 2130772137;
			
			// aapt resource value: 0x7f0100a8
			public const int actionViewClass = 2130772136;
			
			// aapt resource value: 0x7f01012e
			public const int activateOnDefaultValues = 2130772270;
			
			// aapt resource value: 0x7f010124
			public const int activeColor = 2130772260;
			
			// aapt resource value: 0x7f010061
			public const int activityChooserViewStyle = 2130772065;
			
			// aapt resource value: 0x7f010084
			public const int alertDialogButtonGroupStyle = 2130772100;
			
			// aapt resource value: 0x7f010085
			public const int alertDialogCenterButtons = 2130772101;
			
			// aapt resource value: 0x7f010083
			public const int alertDialogStyle = 2130772099;
			
			// aapt resource value: 0x7f010086
			public const int alertDialogTheme = 2130772102;
			
			// aapt resource value: 0x7f010098
			public const int allowStacking = 2130772120;
			
			// aapt resource value: 0x7f01011f
			public const int alwaysActive = 2130772255;
			
			// aapt resource value: 0x7f01009f
			public const int arrowHeadLength = 2130772127;
			
			// aapt resource value: 0x7f0100a0
			public const int arrowShaftLength = 2130772128;
			
			// aapt resource value: 0x7f01008b
			public const int autoCompleteTextViewStyle = 2130772107;
			
			// aapt resource value: 0x7f010010
			public const int background = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int backgroundSplit = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int backgroundStacked = 2130771985;
			
			// aapt resource value: 0x7f0100d3
			public const int backgroundTint = 2130772179;
			
			// aapt resource value: 0x7f0100d4
			public const int backgroundTintMode = 2130772180;
			
			// aapt resource value: 0x7f010122
			public const int barHeight = 2130772258;
			
			// aapt resource value: 0x7f0100a1
			public const int barLength = 2130772129;
			
			// aapt resource value: 0x7f0100d9
			public const int behavior_hideable = 2130772185;
			
			// aapt resource value: 0x7f0100ff
			public const int behavior_overlapTop = 2130772223;
			
			// aapt resource value: 0x7f0100d8
			public const int behavior_peekHeight = 2130772184;
			
			// aapt resource value: 0x7f0100f5
			public const int borderWidth = 2130772213;
			
			// aapt resource value: 0x7f01005e
			public const int borderlessButtonStyle = 2130772062;
			
			// aapt resource value: 0x7f0100ef
			public const int bottomSheetDialogTheme = 2130772207;
			
			// aapt resource value: 0x7f0100f0
			public const int bottomSheetStyle = 2130772208;
			
			// aapt resource value: 0x7f01005b
			public const int buttonBarButtonStyle = 2130772059;
			
			// aapt resource value: 0x7f010089
			public const int buttonBarNegativeButtonStyle = 2130772105;
			
			// aapt resource value: 0x7f01008a
			public const int buttonBarNeutralButtonStyle = 2130772106;
			
			// aapt resource value: 0x7f010088
			public const int buttonBarPositiveButtonStyle = 2130772104;
			
			// aapt resource value: 0x7f01005a
			public const int buttonBarStyle = 2130772058;
			
			// aapt resource value: 0x7f010023
			public const int buttonPanelSideLayout = 2130772003;
			
			// aapt resource value: 0x7f01008c
			public const int buttonStyle = 2130772108;
			
			// aapt resource value: 0x7f01008d
			public const int buttonStyleSmall = 2130772109;
			
			// aapt resource value: 0x7f010099
			public const int buttonTint = 2130772121;
			
			// aapt resource value: 0x7f01009a
			public const int buttonTintMode = 2130772122;
			
			// aapt resource value: 0x7f01008e
			public const int checkboxStyle = 2130772110;
			
			// aapt resource value: 0x7f01008f
			public const int checkedTextViewStyle = 2130772111;
			
			// aapt resource value: 0x7f0100b1
			public const int closeIcon = 2130772145;
			
			// aapt resource value: 0x7f010020
			public const int closeItemLayout = 2130772000;
			
			// aapt resource value: 0x7f0100ca
			public const int collapseContentDescription = 2130772170;
			
			// aapt resource value: 0x7f0100c9
			public const int collapseIcon = 2130772169;
			
			// aapt resource value: 0x7f0100e6
			public const int collapsedTitleGravity = 2130772198;
			
			// aapt resource value: 0x7f0100e2
			public const int collapsedTitleTextAppearance = 2130772194;
			
			// aapt resource value: 0x7f01009b
			public const int color = 2130772123;
			
			// aapt resource value: 0x7f01007c
			public const int colorAccent = 2130772092;
			
			// aapt resource value: 0x7f010080
			public const int colorButtonNormal = 2130772096;
			
			// aapt resource value: 0x7f01007e
			public const int colorControlActivated = 2130772094;
			
			// aapt resource value: 0x7f01007f
			public const int colorControlHighlight = 2130772095;
			
			// aapt resource value: 0x7f01007d
			public const int colorControlNormal = 2130772093;
			
			// aapt resource value: 0x7f01007a
			public const int colorPrimary = 2130772090;
			
			// aapt resource value: 0x7f01007b
			public const int colorPrimaryDark = 2130772091;
			
			// aapt resource value: 0x7f010081
			public const int colorSwitchThumbNormal = 2130772097;
			
			// aapt resource value: 0x7f0100b6
			public const int commitIcon = 2130772150;
			
			// aapt resource value: 0x7f01001b
			public const int contentInsetEnd = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int contentInsetLeft = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int contentInsetRight = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int contentInsetStart = 2130771994;
			
			// aapt resource value: 0x7f0100e3
			public const int contentScrim = 2130772195;
			
			// aapt resource value: 0x7f010082
			public const int controlBackground = 2130772098;
			
			// aapt resource value: 0x7f010115
			public const int counterEnabled = 2130772245;
			
			// aapt resource value: 0x7f010116
			public const int counterMaxLength = 2130772246;
			
			// aapt resource value: 0x7f010118
			public const int counterOverflowTextAppearance = 2130772248;
			
			// aapt resource value: 0x7f010117
			public const int counterTextAppearance = 2130772247;
			
			// aapt resource value: 0x7f010013
			public const int customNavigationLayout = 2130771987;
			
			// aapt resource value: 0x7f010123
			public const int defaultColor = 2130772259;
			
			// aapt resource value: 0x7f0100b0
			public const int defaultQueryHint = 2130772144;
			
			// aapt resource value: 0x7f010053
			public const int dialogPreferredPadding = 2130772051;
			
			// aapt resource value: 0x7f010052
			public const int dialogTheme = 2130772050;
			
			// aapt resource value: 0x7f010009
			public const int displayOptions = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int divider = 2130771983;
			
			// aapt resource value: 0x7f010060
			public const int dividerHorizontal = 2130772064;
			
			// aapt resource value: 0x7f0100a5
			public const int dividerPadding = 2130772133;
			
			// aapt resource value: 0x7f01005f
			public const int dividerVertical = 2130772063;
			
			// aapt resource value: 0x7f01009d
			public const int drawableSize = 2130772125;
			
			// aapt resource value: 0x7f010004
			public const int drawerArrowStyle = 2130771972;
			
			// aapt resource value: 0x7f010072
			public const int dropDownListViewStyle = 2130772082;
			
			// aapt resource value: 0x7f010056
			public const int dropdownListPreferredItemHeight = 2130772054;
			
			// aapt resource value: 0x7f010067
			public const int editTextBackground = 2130772071;
			
			// aapt resource value: 0x7f010066
			public const int editTextColor = 2130772070;
			
			// aapt resource value: 0x7f010090
			public const int editTextStyle = 2130772112;
			
			// aapt resource value: 0x7f01001e
			public const int elevation = 2130771998;
			
			// aapt resource value: 0x7f010113
			public const int errorEnabled = 2130772243;
			
			// aapt resource value: 0x7f010114
			public const int errorTextAppearance = 2130772244;
			
			// aapt resource value: 0x7f010022
			public const int expandActivityOverflowButtonDrawable = 2130772002;
			
			// aapt resource value: 0x7f0100d5
			public const int expanded = 2130772181;
			
			// aapt resource value: 0x7f0100e7
			public const int expandedTitleGravity = 2130772199;
			
			// aapt resource value: 0x7f0100dc
			public const int expandedTitleMargin = 2130772188;
			
			// aapt resource value: 0x7f0100e0
			public const int expandedTitleMarginBottom = 2130772192;
			
			// aapt resource value: 0x7f0100df
			public const int expandedTitleMarginEnd = 2130772191;
			
			// aapt resource value: 0x7f0100dd
			public const int expandedTitleMarginStart = 2130772189;
			
			// aapt resource value: 0x7f0100de
			public const int expandedTitleMarginTop = 2130772190;
			
			// aapt resource value: 0x7f0100e1
			public const int expandedTitleTextAppearance = 2130772193;
			
			// aapt resource value: 0x7f0100f3
			public const int fabSize = 2130772211;
			
			// aapt resource value: 0x7f0100f7
			public const int foregroundInsidePadding = 2130772215;
			
			// aapt resource value: 0x7f01009e
			public const int gapBetweenBars = 2130772126;
			
			// aapt resource value: 0x7f0100b2
			public const int goIcon = 2130772146;
			
			// aapt resource value: 0x7f0100fd
			public const int headerLayout = 2130772221;
			
			// aapt resource value: 0x7f010005
			public const int height = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int hideOnContentScroll = 2130771993;
			
			// aapt resource value: 0x7f010119
			public const int hintAnimationEnabled = 2130772249;
			
			// aapt resource value: 0x7f010112
			public const int hintEnabled = 2130772242;
			
			// aapt resource value: 0x7f010111
			public const int hintTextAppearance = 2130772241;
			
			// aapt resource value: 0x7f010058
			public const int homeAsUpIndicator = 2130772056;
			
			// aapt resource value: 0x7f010014
			public const int homeLayout = 2130771988;
			
			// aapt resource value: 0x7f01000d
			public const int icon = 2130771981;
			
			// aapt resource value: 0x7f0100ae
			public const int iconifiedByDefault = 2130772142;
			
			// aapt resource value: 0x7f010068
			public const int imageButtonStyle = 2130772072;
			
			// aapt resource value: 0x7f010016
			public const int indeterminateProgressStyle = 2130771990;
			
			// aapt resource value: 0x7f010021
			public const int initialActivityCount = 2130772001;
			
			// aapt resource value: 0x7f0100fe
			public const int insetForeground = 2130772222;
			
			// aapt resource value: 0x7f010121
			public const int internalPadding = 2130772257;
			
			// aapt resource value: 0x7f010006
			public const int isLightTheme = 2130771974;
			
			// aapt resource value: 0x7f0100fb
			public const int itemBackground = 2130772219;
			
			// aapt resource value: 0x7f0100f9
			public const int itemIconTint = 2130772217;
			
			// aapt resource value: 0x7f010018
			public const int itemPadding = 2130771992;
			
			// aapt resource value: 0x7f0100fc
			public const int itemTextAppearance = 2130772220;
			
			// aapt resource value: 0x7f0100fa
			public const int itemTextColor = 2130772218;
			
			// aapt resource value: 0x7f0100e9
			public const int keylines = 2130772201;
			
			// aapt resource value: 0x7f0100ad
			public const int layout = 2130772141;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f0100ec
			public const int layout_anchor = 2130772204;
			
			// aapt resource value: 0x7f0100ee
			public const int layout_anchorGravity = 2130772206;
			
			// aapt resource value: 0x7f0100eb
			public const int layout_behavior = 2130772203;
			
			// aapt resource value: 0x7f0100da
			public const int layout_collapseMode = 2130772186;
			
			// aapt resource value: 0x7f0100db
			public const int layout_collapseParallaxMultiplier = 2130772187;
			
			// aapt resource value: 0x7f0100ed
			public const int layout_keyline = 2130772205;
			
			// aapt resource value: 0x7f0100d6
			public const int layout_scrollFlags = 2130772182;
			
			// aapt resource value: 0x7f0100d7
			public const int layout_scrollInterpolator = 2130772183;
			
			// aapt resource value: 0x7f010079
			public const int listChoiceBackgroundIndicator = 2130772089;
			
			// aapt resource value: 0x7f010054
			public const int listDividerAlertDialog = 2130772052;
			
			// aapt resource value: 0x7f010027
			public const int listItemLayout = 2130772007;
			
			// aapt resource value: 0x7f010024
			public const int listLayout = 2130772004;
			
			// aapt resource value: 0x7f010073
			public const int listPopupWindowStyle = 2130772083;
			
			// aapt resource value: 0x7f01006d
			public const int listPreferredItemHeight = 2130772077;
			
			// aapt resource value: 0x7f01006f
			public const int listPreferredItemHeightLarge = 2130772079;
			
			// aapt resource value: 0x7f01006e
			public const int listPreferredItemHeightSmall = 2130772078;
			
			// aapt resource value: 0x7f010070
			public const int listPreferredItemPaddingLeft = 2130772080;
			
			// aapt resource value: 0x7f010071
			public const int listPreferredItemPaddingRight = 2130772081;
			
			// aapt resource value: 0x7f01000e
			public const int logo = 2130771982;
			
			// aapt resource value: 0x7f0100cd
			public const int logoDescription = 2130772173;
			
			// aapt resource value: 0x7f010132
			public const int materialUI = 2130772274;
			
			// aapt resource value: 0x7f010100
			public const int maxActionInlineWidth = 2130772224;
			
			// aapt resource value: 0x7f0100c8
			public const int maxButtonHeight = 2130772168;
			
			// aapt resource value: 0x7f01011d
			public const int maxThumbHidden = 2130772253;
			
			// aapt resource value: 0x7f0100a3
			public const int measureWithLargestChild = 2130772131;
			
			// aapt resource value: 0x7f0100f8
			public const int menu = 2130772216;
			
			// aapt resource value: 0x7f01011c
			public const int minThumbHidden = 2130772252;
			
			// aapt resource value: 0x7f010025
			public const int multiChoiceItemLayout = 2130772005;
			
			// aapt resource value: 0x7f0100cc
			public const int navigationContentDescription = 2130772172;
			
			// aapt resource value: 0x7f0100cb
			public const int navigationIcon = 2130772171;
			
			// aapt resource value: 0x7f010008
			public const int navigationMode = 2130771976;
			
			// aapt resource value: 0x7f0100ab
			public const int overlapAnchor = 2130772139;
			
			// aapt resource value: 0x7f0100d1
			public const int paddingEnd = 2130772177;
			
			// aapt resource value: 0x7f0100d0
			public const int paddingStart = 2130772176;
			
			// aapt resource value: 0x7f010076
			public const int panelBackground = 2130772086;
			
			// aapt resource value: 0x7f010078
			public const int panelMenuListTheme = 2130772088;
			
			// aapt resource value: 0x7f010077
			public const int panelMenuListWidth = 2130772087;
			
			// aapt resource value: 0x7f010064
			public const int popupMenuStyle = 2130772068;
			
			// aapt resource value: 0x7f01001f
			public const int popupTheme = 2130771999;
			
			// aapt resource value: 0x7f010065
			public const int popupWindowStyle = 2130772069;
			
			// aapt resource value: 0x7f0100aa
			public const int preserveIconSpacing = 2130772138;
			
			// aapt resource value: 0x7f0100f4
			public const int pressedTranslationZ = 2130772212;
			
			// aapt resource value: 0x7f010017
			public const int progressBarPadding = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int progressBarStyle = 2130771989;
			
			// aapt resource value: 0x7f0100b8
			public const int queryBackground = 2130772152;
			
			// aapt resource value: 0x7f0100af
			public const int queryHint = 2130772143;
			
			// aapt resource value: 0x7f010091
			public const int radioButtonStyle = 2130772113;
			
			// aapt resource value: 0x7f010092
			public const int ratingBarStyle = 2130772114;
			
			// aapt resource value: 0x7f010093
			public const int ratingBarStyleIndicator = 2130772115;
			
			// aapt resource value: 0x7f010094
			public const int ratingBarStyleSmall = 2130772116;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f0100f2
			public const int rippleColor = 2130772210;
			
			// aapt resource value: 0x7f0100b4
			public const int searchHintIcon = 2130772148;
			
			// aapt resource value: 0x7f0100b3
			public const int searchIcon = 2130772147;
			
			// aapt resource value: 0x7f01006c
			public const int searchViewStyle = 2130772076;
			
			// aapt resource value: 0x7f010095
			public const int seekBarStyle = 2130772117;
			
			// aapt resource value: 0x7f01005c
			public const int selectableItemBackground = 2130772060;
			
			// aapt resource value: 0x7f01005d
			public const int selectableItemBackgroundBorderless = 2130772061;
			
			// aapt resource value: 0x7f0100a6
			public const int showAsAction = 2130772134;
			
			// aapt resource value: 0x7f0100a4
			public const int showDividers = 2130772132;
			
			// aapt resource value: 0x7f01011e
			public const int showRangeLabels = 2130772254;
			
			// aapt resource value: 0x7f0100c0
			public const int showText = 2130772160;
			
			// aapt resource value: 0x7f010026
			public const int singleChoiceItemLayout = 2130772006;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f01009c
			public const int spinBars = 2130772124;
			
			// aapt resource value: 0x7f010057
			public const int spinnerDropDownItemStyle = 2130772055;
			
			// aapt resource value: 0x7f010096
			public const int spinnerStyle = 2130772118;
			
			// aapt resource value: 0x7f0100bf
			public const int splitTrack = 2130772159;
			
			// aapt resource value: 0x7f010028
			public const int srcCompat = 2130772008;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f0100ac
			public const int state_above_anchor = 2130772140;
			
			// aapt resource value: 0x7f0100ea
			public const int statusBarBackground = 2130772202;
			
			// aapt resource value: 0x7f0100e4
			public const int statusBarScrim = 2130772196;
			
			// aapt resource value: 0x7f01012f
			public const int stepValue = 2130772271;
			
			// aapt resource value: 0x7f010130
			public const int stepValueContinuously = 2130772272;
			
			// aapt resource value: 0x7f0100b9
			public const int submitBackground = 2130772153;
			
			// aapt resource value: 0x7f01000a
			public const int subtitle = 2130771978;
			
			// aapt resource value: 0x7f0100c2
			public const int subtitleTextAppearance = 2130772162;
			
			// aapt resource value: 0x7f0100cf
			public const int subtitleTextColor = 2130772175;
			
			// aapt resource value: 0x7f01000c
			public const int subtitleTextStyle = 2130771980;
			
			// aapt resource value: 0x7f0100b7
			public const int suggestionRowLayout = 2130772151;
			
			// aapt resource value: 0x7f0100bd
			public const int switchMinWidth = 2130772157;
			
			// aapt resource value: 0x7f0100be
			public const int switchPadding = 2130772158;
			
			// aapt resource value: 0x7f010097
			public const int switchStyle = 2130772119;
			
			// aapt resource value: 0x7f0100bc
			public const int switchTextAppearance = 2130772156;
			
			// aapt resource value: 0x7f010104
			public const int tabBackground = 2130772228;
			
			// aapt resource value: 0x7f010103
			public const int tabContentStart = 2130772227;
			
			// aapt resource value: 0x7f010106
			public const int tabGravity = 2130772230;
			
			// aapt resource value: 0x7f010101
			public const int tabIndicatorColor = 2130772225;
			
			// aapt resource value: 0x7f010102
			public const int tabIndicatorHeight = 2130772226;
			
			// aapt resource value: 0x7f010108
			public const int tabMaxWidth = 2130772232;
			
			// aapt resource value: 0x7f010107
			public const int tabMinWidth = 2130772231;
			
			// aapt resource value: 0x7f010105
			public const int tabMode = 2130772229;
			
			// aapt resource value: 0x7f010110
			public const int tabPadding = 2130772240;
			
			// aapt resource value: 0x7f01010f
			public const int tabPaddingBottom = 2130772239;
			
			// aapt resource value: 0x7f01010e
			public const int tabPaddingEnd = 2130772238;
			
			// aapt resource value: 0x7f01010c
			public const int tabPaddingStart = 2130772236;
			
			// aapt resource value: 0x7f01010d
			public const int tabPaddingTop = 2130772237;
			
			// aapt resource value: 0x7f01010b
			public const int tabSelectedTextColor = 2130772235;
			
			// aapt resource value: 0x7f010109
			public const int tabTextAppearance = 2130772233;
			
			// aapt resource value: 0x7f01010a
			public const int tabTextColor = 2130772234;
			
			// aapt resource value: 0x7f010125
			public const int textAboveThumbsColor = 2130772261;
			
			// aapt resource value: 0x7f010029
			public const int textAllCaps = 2130772009;
			
			// aapt resource value: 0x7f010050
			public const int textAppearanceLargePopupMenu = 2130772048;
			
			// aapt resource value: 0x7f010074
			public const int textAppearanceListItem = 2130772084;
			
			// aapt resource value: 0x7f010075
			public const int textAppearanceListItemSmall = 2130772085;
			
			// aapt resource value: 0x7f01006a
			public const int textAppearanceSearchResultSubtitle = 2130772074;
			
			// aapt resource value: 0x7f010069
			public const int textAppearanceSearchResultTitle = 2130772073;
			
			// aapt resource value: 0x7f010051
			public const int textAppearanceSmallPopupMenu = 2130772049;
			
			// aapt resource value: 0x7f010087
			public const int textColorAlertDialogListItem = 2130772103;
			
			// aapt resource value: 0x7f0100f1
			public const int textColorError = 2130772209;
			
			// aapt resource value: 0x7f01006b
			public const int textColorSearchUrl = 2130772075;
			
			// aapt resource value: 0x7f010131
			public const int textSize = 2130772273;
			
			// aapt resource value: 0x7f0100d2
			public const int theme = 2130772178;
			
			// aapt resource value: 0x7f0100a2
			public const int thickness = 2130772130;
			
			// aapt resource value: 0x7f010128
			public const int thumbDisabled = 2130772264;
			
			// aapt resource value: 0x7f010126
			public const int thumbNormal = 2130772262;
			
			// aapt resource value: 0x7f010127
			public const int thumbPressed = 2130772263;
			
			// aapt resource value: 0x7f010129
			public const int thumbShadow = 2130772265;
			
			// aapt resource value: 0x7f01012d
			public const int thumbShadowBlur = 2130772269;
			
			// aapt resource value: 0x7f01012a
			public const int thumbShadowColor = 2130772266;
			
			// aapt resource value: 0x7f01012b
			public const int thumbShadowXOffset = 2130772267;
			
			// aapt resource value: 0x7f01012c
			public const int thumbShadowYOffset = 2130772268;
			
			// aapt resource value: 0x7f0100bb
			public const int thumbTextPadding = 2130772155;
			
			// aapt resource value: 0x7f010007
			public const int title = 2130771975;
			
			// aapt resource value: 0x7f0100e8
			public const int titleEnabled = 2130772200;
			
			// aapt resource value: 0x7f0100c7
			public const int titleMarginBottom = 2130772167;
			
			// aapt resource value: 0x7f0100c5
			public const int titleMarginEnd = 2130772165;
			
			// aapt resource value: 0x7f0100c4
			public const int titleMarginStart = 2130772164;
			
			// aapt resource value: 0x7f0100c6
			public const int titleMarginTop = 2130772166;
			
			// aapt resource value: 0x7f0100c3
			public const int titleMargins = 2130772163;
			
			// aapt resource value: 0x7f0100c1
			public const int titleTextAppearance = 2130772161;
			
			// aapt resource value: 0x7f0100ce
			public const int titleTextColor = 2130772174;
			
			// aapt resource value: 0x7f01000b
			public const int titleTextStyle = 2130771979;
			
			// aapt resource value: 0x7f0100e5
			public const int toolbarId = 2130772197;
			
			// aapt resource value: 0x7f010063
			public const int toolbarNavigationButtonStyle = 2130772067;
			
			// aapt resource value: 0x7f010062
			public const int toolbarStyle = 2130772066;
			
			// aapt resource value: 0x7f0100ba
			public const int track = 2130772154;
			
			// aapt resource value: 0x7f0100f6
			public const int useCompatPadding = 2130772214;
			
			// aapt resource value: 0x7f010120
			public const int valuesAboveThumbs = 2130772256;
			
			// aapt resource value: 0x7f0100b5
			public const int voiceIcon = 2130772149;
			
			// aapt resource value: 0x7f01002a
			public const int windowActionBar = 2130772010;
			
			// aapt resource value: 0x7f01002c
			public const int windowActionBarOverlay = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int windowActionModeOverlay = 2130772013;
			
			// aapt resource value: 0x7f010031
			public const int windowFixedHeightMajor = 2130772017;
			
			// aapt resource value: 0x7f01002f
			public const int windowFixedHeightMinor = 2130772015;
			
			// aapt resource value: 0x7f01002e
			public const int windowFixedWidthMajor = 2130772014;
			
			// aapt resource value: 0x7f010030
			public const int windowFixedWidthMinor = 2130772016;
			
			// aapt resource value: 0x7f010032
			public const int windowMinWidthMajor = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int windowMinWidthMinor = 2130772019;
			
			// aapt resource value: 0x7f01002b
			public const int windowNoTitle = 2130772011;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090003
			public const int abc_action_bar_embed_tabs = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int abc_action_bar_embed_tabs_pre_jb = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int abc_action_bar_expanded_action_views_exclusive = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int abc_allow_stacked_button_bar = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int abc_config_actionMenuItemAllCaps = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int abc_config_allowActionMenuItemTextWithIcon = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int abc_config_closeDialogWhenTouchOutside = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131296263;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0c0044
			public const int abc_background_cache_hint_selector_material_dark = 2131492932;
			
			// aapt resource value: 0x7f0c0045
			public const int abc_background_cache_hint_selector_material_light = 2131492933;
			
			// aapt resource value: 0x7f0c0000
			public const int abc_input_method_navigation_guard = 2131492864;
			
			// aapt resource value: 0x7f0c0046
			public const int abc_primary_text_disable_only_material_dark = 2131492934;
			
			// aapt resource value: 0x7f0c0047
			public const int abc_primary_text_disable_only_material_light = 2131492935;
			
			// aapt resource value: 0x7f0c0048
			public const int abc_primary_text_material_dark = 2131492936;
			
			// aapt resource value: 0x7f0c0049
			public const int abc_primary_text_material_light = 2131492937;
			
			// aapt resource value: 0x7f0c004a
			public const int abc_search_url_text = 2131492938;
			
			// aapt resource value: 0x7f0c0001
			public const int abc_search_url_text_normal = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int abc_search_url_text_pressed = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int abc_search_url_text_selected = 2131492867;
			
			// aapt resource value: 0x7f0c004b
			public const int abc_secondary_text_material_dark = 2131492939;
			
			// aapt resource value: 0x7f0c004c
			public const int abc_secondary_text_material_light = 2131492940;
			
			// aapt resource value: 0x7f0c0004
			public const int accent_material_dark = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int accent_material_light = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int background_floating_material_dark = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public const int background_floating_material_light = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int background_material_dark = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int background_material_light = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int bright_foreground_disabled_material_dark = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public const int bright_foreground_disabled_material_light = 2131492875;
			
			// aapt resource value: 0x7f0c000c
			public const int bright_foreground_inverse_material_dark = 2131492876;
			
			// aapt resource value: 0x7f0c000d
			public const int bright_foreground_inverse_material_light = 2131492877;
			
			// aapt resource value: 0x7f0c000e
			public const int bright_foreground_material_dark = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int bright_foreground_material_light = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int button_material_dark = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int button_material_light = 2131492881;
			
			// aapt resource value: 0x7f0c003a
			public const int design_fab_shadow_end_color = 2131492922;
			
			// aapt resource value: 0x7f0c003b
			public const int design_fab_shadow_mid_color = 2131492923;
			
			// aapt resource value: 0x7f0c003c
			public const int design_fab_shadow_start_color = 2131492924;
			
			// aapt resource value: 0x7f0c003d
			public const int design_fab_stroke_end_inner_color = 2131492925;
			
			// aapt resource value: 0x7f0c003e
			public const int design_fab_stroke_end_outer_color = 2131492926;
			
			// aapt resource value: 0x7f0c003f
			public const int design_fab_stroke_top_inner_color = 2131492927;
			
			// aapt resource value: 0x7f0c0040
			public const int design_fab_stroke_top_outer_color = 2131492928;
			
			// aapt resource value: 0x7f0c0041
			public const int design_snackbar_background_color = 2131492929;
			
			// aapt resource value: 0x7f0c0042
			public const int design_textinput_error_color_dark = 2131492930;
			
			// aapt resource value: 0x7f0c0043
			public const int design_textinput_error_color_light = 2131492931;
			
			// aapt resource value: 0x7f0c0012
			public const int dim_foreground_disabled_material_dark = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int dim_foreground_disabled_material_light = 2131492883;
			
			// aapt resource value: 0x7f0c0014
			public const int dim_foreground_material_dark = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int dim_foreground_material_light = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int foreground_material_dark = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public const int foreground_material_light = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public const int highlighted_text_material_dark = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public const int highlighted_text_material_light = 2131492889;
			
			// aapt resource value: 0x7f0c001a
			public const int hint_foreground_material_dark = 2131492890;
			
			// aapt resource value: 0x7f0c001b
			public const int hint_foreground_material_light = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public const int material_blue_grey_800 = 2131492892;
			
			// aapt resource value: 0x7f0c001d
			public const int material_blue_grey_900 = 2131492893;
			
			// aapt resource value: 0x7f0c001e
			public const int material_blue_grey_950 = 2131492894;
			
			// aapt resource value: 0x7f0c001f
			public const int material_deep_teal_200 = 2131492895;
			
			// aapt resource value: 0x7f0c0020
			public const int material_deep_teal_500 = 2131492896;
			
			// aapt resource value: 0x7f0c0021
			public const int material_grey_100 = 2131492897;
			
			// aapt resource value: 0x7f0c0022
			public const int material_grey_300 = 2131492898;
			
			// aapt resource value: 0x7f0c0023
			public const int material_grey_50 = 2131492899;
			
			// aapt resource value: 0x7f0c0024
			public const int material_grey_600 = 2131492900;
			
			// aapt resource value: 0x7f0c0025
			public const int material_grey_800 = 2131492901;
			
			// aapt resource value: 0x7f0c0026
			public const int material_grey_850 = 2131492902;
			
			// aapt resource value: 0x7f0c0027
			public const int material_grey_900 = 2131492903;
			
			// aapt resource value: 0x7f0c0028
			public const int primary_dark_material_dark = 2131492904;
			
			// aapt resource value: 0x7f0c0029
			public const int primary_dark_material_light = 2131492905;
			
			// aapt resource value: 0x7f0c002a
			public const int primary_material_dark = 2131492906;
			
			// aapt resource value: 0x7f0c002b
			public const int primary_material_light = 2131492907;
			
			// aapt resource value: 0x7f0c002c
			public const int primary_text_default_material_dark = 2131492908;
			
			// aapt resource value: 0x7f0c002d
			public const int primary_text_default_material_light = 2131492909;
			
			// aapt resource value: 0x7f0c002e
			public const int primary_text_disabled_material_dark = 2131492910;
			
			// aapt resource value: 0x7f0c002f
			public const int primary_text_disabled_material_light = 2131492911;
			
			// aapt resource value: 0x7f0c0030
			public const int ripple_material_dark = 2131492912;
			
			// aapt resource value: 0x7f0c0031
			public const int ripple_material_light = 2131492913;
			
			// aapt resource value: 0x7f0c0032
			public const int secondary_text_default_material_dark = 2131492914;
			
			// aapt resource value: 0x7f0c0033
			public const int secondary_text_default_material_light = 2131492915;
			
			// aapt resource value: 0x7f0c0034
			public const int secondary_text_disabled_material_dark = 2131492916;
			
			// aapt resource value: 0x7f0c0035
			public const int secondary_text_disabled_material_light = 2131492917;
			
			// aapt resource value: 0x7f0c0036
			public const int switch_thumb_disabled_material_dark = 2131492918;
			
			// aapt resource value: 0x7f0c0037
			public const int switch_thumb_disabled_material_light = 2131492919;
			
			// aapt resource value: 0x7f0c004d
			public const int switch_thumb_material_dark = 2131492941;
			
			// aapt resource value: 0x7f0c004e
			public const int switch_thumb_material_light = 2131492942;
			
			// aapt resource value: 0x7f0c0038
			public const int switch_thumb_normal_material_dark = 2131492920;
			
			// aapt resource value: 0x7f0c0039
			public const int switch_thumb_normal_material_light = 2131492921;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060010
			public const int abc_action_bar_content_inset_material = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int abc_action_bar_default_height_material = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int abc_action_bar_default_padding_end_material = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int abc_action_bar_default_padding_start_material = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int abc_action_bar_icon_vertical_padding_material = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int abc_action_bar_overflow_padding_end_material = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int abc_action_bar_overflow_padding_start_material = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int abc_action_bar_progress_bar_size = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int abc_action_bar_stacked_max_height = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int abc_action_bar_stacked_tab_max_width = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int abc_action_bar_subtitle_bottom_margin_material = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int abc_action_bar_subtitle_top_margin_material = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int abc_action_button_min_height_material = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int abc_action_button_min_width_material = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int abc_action_button_min_width_overflow_material = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int abc_alert_dialog_button_bar_height = 2131099651;
			
			// aapt resource value: 0x7f06001e
			public const int abc_button_inset_horizontal_material = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int abc_button_inset_vertical_material = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int abc_button_padding_horizontal_material = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int abc_button_padding_vertical_material = 2131099681;
			
			// aapt resource value: 0x7f060008
			public const int abc_config_prefDialogWidth = 2131099656;
			
			// aapt resource value: 0x7f060022
			public const int abc_control_corner_material = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int abc_control_inset_material = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int abc_control_padding_material = 2131099684;
			
			// aapt resource value: 0x7f060009
			public const int abc_dialog_fixed_height_major = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int abc_dialog_fixed_height_minor = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int abc_dialog_fixed_width_major = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int abc_dialog_fixed_width_minor = 2131099660;
			
			// aapt resource value: 0x7f060025
			public const int abc_dialog_list_padding_vertical_material = 2131099685;
			
			// aapt resource value: 0x7f06000d
			public const int abc_dialog_min_width_major = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int abc_dialog_min_width_minor = 2131099662;
			
			// aapt resource value: 0x7f060026
			public const int abc_dialog_padding_material = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int abc_dialog_padding_top_material = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int abc_disabled_alpha_material_dark = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int abc_disabled_alpha_material_light = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int abc_dropdownitem_icon_width = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int abc_dropdownitem_text_padding_left = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int abc_dropdownitem_text_padding_right = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int abc_edit_text_inset_bottom_material = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int abc_edit_text_inset_horizontal_material = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int abc_edit_text_inset_top_material = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int abc_floating_window_z = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int abc_list_item_padding_horizontal_material = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int abc_panel_menu_list_width = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int abc_search_view_preferred_width = 2131099699;
			
			// aapt resource value: 0x7f06000f
			public const int abc_search_view_text_min_width = 2131099663;
			
			// aapt resource value: 0x7f060034
			public const int abc_seekbar_track_background_height_material = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int abc_seekbar_track_progress_height_material = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int abc_select_dialog_padding_start_material = 2131099702;
			
			// aapt resource value: 0x7f060013
			public const int abc_switch_padding = 2131099667;
			
			// aapt resource value: 0x7f060037
			public const int abc_text_size_body_1_material = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int abc_text_size_body_2_material = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int abc_text_size_button_material = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int abc_text_size_caption_material = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int abc_text_size_display_1_material = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int abc_text_size_display_2_material = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int abc_text_size_display_3_material = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int abc_text_size_display_4_material = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int abc_text_size_headline_material = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int abc_text_size_large_material = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int abc_text_size_medium_material = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int abc_text_size_menu_material = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int abc_text_size_small_material = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int abc_text_size_subhead_material = 2131099716;
			
			// aapt resource value: 0x7f060006
			public const int abc_text_size_subtitle_material_toolbar = 2131099654;
			
			// aapt resource value: 0x7f060045
			public const int abc_text_size_title_material = 2131099717;
			
			// aapt resource value: 0x7f060007
			public const int abc_text_size_title_material_toolbar = 2131099655;
			
			// aapt resource value: 0x7f060056
			public const int design_appbar_elevation = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int design_bottom_sheet_modal_elevation = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int design_bottom_sheet_modal_peek_height = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int design_fab_border_width = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int design_fab_elevation = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int design_fab_image_size = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int design_fab_size_mini = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int design_fab_size_normal = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int design_fab_translation_z_pressed = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int design_navigation_elevation = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int design_navigation_icon_padding = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int design_navigation_icon_size = 2131099745;
			
			// aapt resource value: 0x7f06004e
			public const int design_navigation_max_width = 2131099726;
			
			// aapt resource value: 0x7f060062
			public const int design_navigation_padding_bottom = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int design_navigation_separator_vertical_padding = 2131099747;
			
			// aapt resource value: 0x7f06004f
			public const int design_snackbar_action_inline_max_width = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int design_snackbar_background_corner_radius = 2131099728;
			
			// aapt resource value: 0x7f060064
			public const int design_snackbar_elevation = 2131099748;
			
			// aapt resource value: 0x7f060051
			public const int design_snackbar_extra_spacing_horizontal = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int design_snackbar_max_width = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int design_snackbar_min_width = 2131099731;
			
			// aapt resource value: 0x7f060065
			public const int design_snackbar_padding_horizontal = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int design_snackbar_padding_vertical = 2131099750;
			
			// aapt resource value: 0x7f060054
			public const int design_snackbar_padding_vertical_2lines = 2131099732;
			
			// aapt resource value: 0x7f060067
			public const int design_snackbar_text_size = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int design_tab_max_width = 2131099752;
			
			// aapt resource value: 0x7f060055
			public const int design_tab_scrollable_min_width = 2131099733;
			
			// aapt resource value: 0x7f060069
			public const int design_tab_text_size = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int design_tab_text_size_2line = 2131099754;
			
			// aapt resource value: 0x7f060046
			public const int disabled_alpha_material_dark = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int disabled_alpha_material_light = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int highlight_alpha_material_colored = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int highlight_alpha_material_dark = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int highlight_alpha_material_light = 2131099722;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int item_touch_helper_swipe_escape_velocity = 2131099650;
			
			// aapt resource value: 0x7f06004b
			public const int notification_large_icon_height = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int notification_large_icon_width = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int notification_subtext_size = 2131099725;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f0c0021
			public const int action_bar_title = 2131492897;
			
			// aapt resource value: 0x7f0c0042
			public const int action_context_bar = 2131492930;
			
			// aapt resource value: 0x7f0c0055
			public const int action_divider = 2131492949;
			
			// aapt resource value: 0x7f0c0002
			public const int action_menu_divider = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int action_menu_presenter = 2131492867;
			
			// aapt resource value: 0x7f0c003e
			public const int action_mode_bar = 2131492926;
			
			// aapt resource value: 0x7f0c003d
			public const int action_mode_bar_stub = 2131492925;
			
			// aapt resource value: 0x7f0c0023
			public const int action_mode_close_button = 2131492899;
			
			// aapt resource value: 0x7f0c0024
			public const int activity_chooser_view_content = 2131492900;
			
			// aapt resource value: 0x7f0c0030
			public const int alertTitle = 2131492912;
			
			// aapt resource value: 0x7f0c001c
			public const int always = 2131492892;
			
			// aapt resource value: 0x7f0c0019
			public const int beginning = 2131492889;
			
			// aapt resource value: 0x7f0c002b
			public const int buttonPanel = 2131492907;
			
			// aapt resource value: 0x7f0c0052
			public const int cancel_action = 2131492946;
			
			// aapt resource value: 0x7f0c0039
			public const int checkbox = 2131492921;
			
			// aapt resource value: 0x7f0c0058
			public const int chronometer = 2131492952;
			
			// aapt resource value: 0x7f0c001d
			public const int collapseActionView = 2131492893;
			
			// aapt resource value: 0x7f0c0031
			public const int contentPanel = 2131492913;
			
			// aapt resource value: 0x7f0c0037
			public const int custom = 2131492919;
			
			// aapt resource value: 0x7f0c0036
			public const int customPanel = 2131492918;
			
			// aapt resource value: 0x7f0c003f
			public const int decor_content_parent = 2131492927;
			
			// aapt resource value: 0x7f0c0027
			public const int default_activity_button = 2131492903;
			
			// aapt resource value: 0x7f0c000c
			public const int disableHome = 2131492876;
			
			// aapt resource value: 0x7f0c0043
			public const int edit_query = 2131492931;
			
			// aapt resource value: 0x7f0c001a
			public const int end = 2131492890;
			
			// aapt resource value: 0x7f0c005d
			public const int end_padder = 2131492957;
			
			// aapt resource value: 0x7f0c0025
			public const int expand_activities_button = 2131492901;
			
			// aapt resource value: 0x7f0c0038
			public const int expanded_menu = 2131492920;
			
			// aapt resource value: 0x7f0c0004
			public const int home = 2131492868;
			
			// aapt resource value: 0x7f0c000d
			public const int homeAsUp = 2131492877;
			
			// aapt resource value: 0x7f0c0029
			public const int icon = 2131492905;
			
			// aapt resource value: 0x7f0c001e
			public const int ifRoom = 2131492894;
			
			// aapt resource value: 0x7f0c0026
			public const int image = 2131492902;
			
			// aapt resource value: 0x7f0c005c
			public const int info = 2131492956;
			
			// aapt resource value: 0x7f0c0056
			public const int line1 = 2131492950;
			
			// aapt resource value: 0x7f0c005a
			public const int line3 = 2131492954;
			
			// aapt resource value: 0x7f0c0009
			public const int listMode = 2131492873;
			
			// aapt resource value: 0x7f0c0028
			public const int list_item = 2131492904;
			
			// aapt resource value: 0x7f0c0054
			public const int media_actions = 2131492948;
			
			// aapt resource value: 0x7f0c001b
			public const int middle = 2131492891;
			
			// aapt resource value: 0x7f0c0014
			public const int multiply = 2131492884;
			
			// aapt resource value: 0x7f0c0050
			public const int myButton = 2131492944;
			
			// aapt resource value: 0x7f0c001f
			public const int never = 2131492895;
			
			// aapt resource value: 0x7f0c000e
			public const int none = 2131492878;
			
			// aapt resource value: 0x7f0c000a
			public const int normal = 2131492874;
			
			// aapt resource value: 0x7f0c002d
			public const int parentPanel = 2131492909;
			
			// aapt resource value: 0x7f0c0005
			public const int progress_circular = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int progress_horizontal = 2131492870;
			
			// aapt resource value: 0x7f0c003b
			public const int radio = 2131492923;
			
			// aapt resource value: 0x7f0c0015
			public const int screen = 2131492885;
			
			// aapt resource value: 0x7f0c0035
			public const int scrollIndicatorDown = 2131492917;
			
			// aapt resource value: 0x7f0c0032
			public const int scrollIndicatorUp = 2131492914;
			
			// aapt resource value: 0x7f0c0033
			public const int scrollView = 2131492915;
			
			// aapt resource value: 0x7f0c0045
			public const int search_badge = 2131492933;
			
			// aapt resource value: 0x7f0c0044
			public const int search_bar = 2131492932;
			
			// aapt resource value: 0x7f0c0046
			public const int search_button = 2131492934;
			
			// aapt resource value: 0x7f0c004b
			public const int search_close_btn = 2131492939;
			
			// aapt resource value: 0x7f0c0047
			public const int search_edit_frame = 2131492935;
			
			// aapt resource value: 0x7f0c004d
			public const int search_go_btn = 2131492941;
			
			// aapt resource value: 0x7f0c0048
			public const int search_mag_icon = 2131492936;
			
			// aapt resource value: 0x7f0c0049
			public const int search_plate = 2131492937;
			
			// aapt resource value: 0x7f0c004a
			public const int search_src_text = 2131492938;
			
			// aapt resource value: 0x7f0c004e
			public const int search_voice_btn = 2131492942;
			
			// aapt resource value: 0x7f0c004f
			public const int select_dialog_listview = 2131492943;
			
			// aapt resource value: 0x7f0c003a
			public const int shortcut = 2131492922;
			
			// aapt resource value: 0x7f0c000f
			public const int showCustom = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int showHome = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int showTitle = 2131492881;
			
			// aapt resource value: 0x7f0c002c
			public const int spacer = 2131492908;
			
			// aapt resource value: 0x7f0c0007
			public const int split_action_bar = 2131492871;
			
			// aapt resource value: 0x7f0c0016
			public const int src_atop = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public const int src_in = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public const int src_over = 2131492888;
			
			// aapt resource value: 0x7f0c0053
			public const int status_bar_latest_event_content = 2131492947;
			
			// aapt resource value: 0x7f0c004c
			public const int submit_area = 2131492940;
			
			// aapt resource value: 0x7f0c000b
			public const int tabMode = 2131492875;
			
			// aapt resource value: 0x7f0c005b
			public const int text = 2131492955;
			
			// aapt resource value: 0x7f0c0059
			public const int text2 = 2131492953;
			
			// aapt resource value: 0x7f0c0034
			public const int textSpacerNoButtons = 2131492916;
			
			// aapt resource value: 0x7f0c0057
			public const int time = 2131492951;
			
			// aapt resource value: 0x7f0c002a
			public const int title = 2131492906;
			
			// aapt resource value: 0x7f0c002f
			public const int title_template = 2131492911;
			
			// aapt resource value: 0x7f0c002e
			public const int topPanel = 2131492910;
			
			// aapt resource value: 0x7f0c0008
			public const int up = 2131492872;
			
			// aapt resource value: 0x7f0c0012
			public const int useLogo = 2131492882;
			
			// aapt resource value: 0x7f0c0020
			public const int withText = 2131492896;
			
			// aapt resource value: 0x7f0c0013
			public const int wrap_content = 2131492883;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0001
			public const int abc_config_activityDefaultDur = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int abc_config_activityShortDur = 2131427330;
			
			// aapt resource value: 0x7f0b0000
			public const int abc_max_action_buttons = 2131427328;
			
			// aapt resource value: 0x7f0b0006
			public const int bottom_sheet_slide_duration = 2131427334;
			
			// aapt resource value: 0x7f0b0003
			public const int cancel_button_image_alpha = 2131427331;
			
			// aapt resource value: 0x7f0b0005
			public const int design_snackbar_text_max_lines = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int status_bar_notification_info_maxnum = 2131427332;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0001
			public const int abc_config_activityDefaultDur = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int abc_config_activityShortDur = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int abc_max_action_buttons = 2131361792;
			
			// aapt resource value: 0x7f0a0003
			public const int cancel_button_image_alpha = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int status_bar_notification_info_maxnum = 2131361796;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f04001e
			public const int design_menu_item_action_area = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int design_navigation_item = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int design_navigation_item_header = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int design_navigation_item_separator = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int design_navigation_item_subheader = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int design_navigation_menu = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int design_navigation_menu_item = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int Main = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int notification_media_action = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int notification_media_cancel_action = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int notification_template_big_media = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int notification_template_big_media_narrow = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int notification_template_lines = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int notification_template_media = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int notification_template_part_chronometer = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int notification_template_part_time = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int select_dialog_item_material = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int select_dialog_multichoice_material = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int select_dialog_singlechoice_material = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int support_simple_spinner_dropdown_item = 2130968625;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0d0000
			public const int action_menu = 2131558400;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
