#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ABCEnjoy.Resource", IsApplication=true)]

namespace ABCEnjoy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int abc_fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int abc_grow_fade_in_from_bottom = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int abc_popup_enter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int abc_popup_exit = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int abc_shrink_fade_out_from_bottom = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int abc_slide_in_bottom = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int abc_slide_in_top = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int abc_slide_out_bottom = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int abc_slide_out_top = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int tooltip_enter = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tooltip_exit = 2131034123;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int abc_allow_stacked_button_bar = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int abc_config_actionMenuItemAllCaps = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int abc_config_closeDialogWhenTouchOutside = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131296260;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0a003e
			public const int abc_background_cache_hint_selector_material_dark = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int abc_background_cache_hint_selector_material_light = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int abc_btn_colored_borderless_text_material = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int abc_btn_colored_text_material = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int abc_color_highlight_material = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int abc_hint_foreground_material_dark = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int abc_hint_foreground_material_light = 2131361860;
			
			// aapt resource value: 0x7f0a0000
			public const int abc_input_method_navigation_guard = 2131361792;
			
			// aapt resource value: 0x7f0a0045
			public const int abc_primary_text_disable_only_material_dark = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public const int abc_primary_text_disable_only_material_light = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int abc_primary_text_material_dark = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int abc_primary_text_material_light = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int abc_search_url_text = 2131361865;
			
			// aapt resource value: 0x7f0a0001
			public const int abc_search_url_text_normal = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int abc_search_url_text_pressed = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int abc_search_url_text_selected = 2131361795;
			
			// aapt resource value: 0x7f0a004a
			public const int abc_secondary_text_material_dark = 2131361866;
			
			// aapt resource value: 0x7f0a004b
			public const int abc_secondary_text_material_light = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int abc_tint_btn_checkable = 2131361868;
			
			// aapt resource value: 0x7f0a004d
			public const int abc_tint_default = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int abc_tint_edittext = 2131361870;
			
			// aapt resource value: 0x7f0a004f
			public const int abc_tint_seek_thumb = 2131361871;
			
			// aapt resource value: 0x7f0a0050
			public const int abc_tint_spinner = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int abc_tint_switch_track = 2131361873;
			
			// aapt resource value: 0x7f0a0004
			public const int accent_material_dark = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int accent_material_light = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int background_floating_material_dark = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int background_floating_material_light = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int background_material_dark = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int background_material_light = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int bright_foreground_disabled_material_dark = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int bright_foreground_disabled_material_light = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int bright_foreground_inverse_material_dark = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int bright_foreground_inverse_material_light = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int bright_foreground_material_dark = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int bright_foreground_material_light = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int button_material_dark = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int button_material_light = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int dim_foreground_disabled_material_dark = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int dim_foreground_disabled_material_light = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int dim_foreground_material_dark = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int dim_foreground_material_light = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int error_color_material = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int foreground_material_dark = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int foreground_material_light = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int highlighted_text_material_dark = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int highlighted_text_material_light = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int material_blue_grey_800 = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int material_blue_grey_900 = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int material_blue_grey_950 = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int material_deep_teal_200 = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int material_deep_teal_500 = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int material_grey_100 = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int material_grey_300 = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int material_grey_50 = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int material_grey_600 = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int material_grey_800 = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int material_grey_850 = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int material_grey_900 = 2131361830;
			
			// aapt resource value: 0x7f0a003c
			public const int notification_action_color_filter = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int notification_icon_bg_color = 2131361853;
			
			// aapt resource value: 0x7f0a003b
			public const int notification_material_background_media_default_color = 2131361851;
			
			// aapt resource value: 0x7f0a0027
			public const int primary_dark_material_dark = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int primary_dark_material_light = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int primary_material_dark = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int primary_material_light = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int primary_text_default_material_dark = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int primary_text_default_material_light = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int primary_text_disabled_material_dark = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int primary_text_disabled_material_light = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int ripple_material_dark = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int ripple_material_light = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int secondary_text_default_material_dark = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int secondary_text_default_material_light = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int secondary_text_disabled_material_dark = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int secondary_text_disabled_material_light = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int switch_thumb_disabled_material_dark = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int switch_thumb_disabled_material_light = 2131361846;
			
			// aapt resource value: 0x7f0a0052
			public const int switch_thumb_material_dark = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int switch_thumb_material_light = 2131361875;
			
			// aapt resource value: 0x7f0a0037
			public const int switch_thumb_normal_material_dark = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public const int switch_thumb_normal_material_light = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int tooltip_background_dark = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int tooltip_background_light = 2131361850;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f07000c
			public const int abc_action_bar_content_inset_material = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int abc_action_bar_content_inset_with_nav = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int abc_action_bar_default_height_material = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int abc_action_bar_default_padding_end_material = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int abc_action_bar_default_padding_start_material = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int abc_action_bar_elevation_material = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int abc_action_bar_icon_vertical_padding_material = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int abc_action_bar_overflow_padding_end_material = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int abc_action_bar_overflow_padding_start_material = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int abc_action_bar_progress_bar_size = 2131165186;
			
			// aapt resource value: 0x7f070015
			public const int abc_action_bar_stacked_max_height = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int abc_action_bar_stacked_tab_max_width = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int abc_action_bar_subtitle_bottom_margin_material = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int abc_action_bar_subtitle_top_margin_material = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int abc_action_button_min_height_material = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int abc_action_button_min_width_material = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int abc_action_button_min_width_overflow_material = 2131165211;
			
			// aapt resource value: 0x7f070000
			public const int abc_alert_dialog_button_bar_height = 2131165184;
			
			// aapt resource value: 0x7f07001c
			public const int abc_button_inset_horizontal_material = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int abc_button_inset_vertical_material = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int abc_button_padding_horizontal_material = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int abc_button_padding_vertical_material = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int abc_cascading_menus_min_smallest_width = 2131165216;
			
			// aapt resource value: 0x7f070005
			public const int abc_config_prefDialogWidth = 2131165189;
			
			// aapt resource value: 0x7f070021
			public const int abc_control_corner_material = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int abc_control_inset_material = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int abc_control_padding_material = 2131165219;
			
			// aapt resource value: 0x7f070006
			public const int abc_dialog_fixed_height_major = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int abc_dialog_fixed_height_minor = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int abc_dialog_fixed_width_major = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int abc_dialog_fixed_width_minor = 2131165193;
			
			// aapt resource value: 0x7f070024
			public const int abc_dialog_list_padding_bottom_no_buttons = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int abc_dialog_list_padding_top_no_title = 2131165221;
			
			// aapt resource value: 0x7f07000a
			public const int abc_dialog_min_width_major = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int abc_dialog_min_width_minor = 2131165195;
			
			// aapt resource value: 0x7f070026
			public const int abc_dialog_padding_material = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int abc_dialog_padding_top_material = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int abc_dialog_title_divider_material = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int abc_disabled_alpha_material_dark = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int abc_disabled_alpha_material_light = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int abc_dropdownitem_icon_width = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int abc_dropdownitem_text_padding_left = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int abc_dropdownitem_text_padding_right = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int abc_edit_text_inset_bottom_material = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int abc_edit_text_inset_horizontal_material = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int abc_edit_text_inset_top_material = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int abc_floating_window_z = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int abc_list_item_padding_horizontal_material = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int abc_panel_menu_list_width = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int abc_progress_bar_height_material = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int abc_search_view_preferred_height = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int abc_search_view_preferred_width = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int abc_seekbar_track_background_height_material = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int abc_seekbar_track_progress_height_material = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int abc_select_dialog_padding_start_material = 2131165241;
			
			// aapt resource value: 0x7f070010
			public const int abc_switch_padding = 2131165200;
			
			// aapt resource value: 0x7f07003a
			public const int abc_text_size_body_1_material = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int abc_text_size_body_2_material = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int abc_text_size_button_material = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int abc_text_size_caption_material = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int abc_text_size_display_1_material = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int abc_text_size_display_2_material = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int abc_text_size_display_3_material = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int abc_text_size_display_4_material = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int abc_text_size_headline_material = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int abc_text_size_large_material = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int abc_text_size_medium_material = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int abc_text_size_menu_header_material = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int abc_text_size_menu_material = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int abc_text_size_small_material = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int abc_text_size_subhead_material = 2131165256;
			
			// aapt resource value: 0x7f070003
			public const int abc_text_size_subtitle_material_toolbar = 2131165187;
			
			// aapt resource value: 0x7f070049
			public const int abc_text_size_title_material = 2131165257;
			
			// aapt resource value: 0x7f070004
			public const int abc_text_size_title_material_toolbar = 2131165188;
			
			// aapt resource value: 0x7f07005f
			public const int compat_button_inset_horizontal_material = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int compat_button_inset_vertical_material = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int compat_button_padding_horizontal_material = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int compat_button_padding_vertical_material = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int compat_control_corner_material = 2131165283;
			
			// aapt resource value: 0x7f07004a
			public const int disabled_alpha_material_dark = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int disabled_alpha_material_light = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int highlight_alpha_material_colored = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int highlight_alpha_material_dark = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int highlight_alpha_material_light = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int hint_alpha_material_dark = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int hint_alpha_material_light = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int hint_pressed_alpha_material_dark = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int hint_pressed_alpha_material_light = 2131165266;
			
			// aapt resource value: 0x7f070064
			public const int notification_action_icon_size = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int notification_action_text_size = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int notification_big_circle_margin = 2131165286;
			
			// aapt resource value: 0x7f07005c
			public const int notification_content_margin_start = 2131165276;
			
			// aapt resource value: 0x7f070067
			public const int notification_large_icon_height = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int notification_large_icon_width = 2131165288;
			
			// aapt resource value: 0x7f07005d
			public const int notification_main_column_padding_top = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int notification_media_narrow_margin = 2131165278;
			
			// aapt resource value: 0x7f070069
			public const int notification_right_icon_size = 2131165289;
			
			// aapt resource value: 0x7f07005b
			public const int notification_right_side_padding_top = 2131165275;
			
			// aapt resource value: 0x7f07006a
			public const int notification_small_icon_background_padding = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int notification_small_icon_size_as_large = 2131165291;
			
			// aapt resource value: 0x7f07006c
			public const int notification_subtext_size = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int notification_top_pad = 2131165293;
			
			// aapt resource value: 0x7f07006e
			public const int notification_top_pad_large_text = 2131165294;
			
			// aapt resource value: 0x7f070053
			public const int tooltip_corner_radius = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int tooltip_horizontal_padding = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int tooltip_margin = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int tooltip_precise_anchor_extra_offset = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int tooltip_precise_anchor_threshold = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int tooltip_vertical_padding = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int tooltip_y_offset_non_touch = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int tooltip_y_offset_touch = 2131165274;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f04001c
			public const int notification_template_big_media = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int notification_template_big_media_narrow = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int notification_template_lines = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int notification_template_media = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int notification_template_part_chronometer = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int notification_template_part_time = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int select_dialog_item_material = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int select_dialog_multichoice_material = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int select_dialog_singlechoice_material = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int support_simple_spinner_dropdown_item = 2130968613;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
